package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * ActionActive generated by hbm2java
 */

public class ActionActive implements java.io.Serializable {

	private int actionActiveId;
	private int permissionRoleId;
	private int actionId;

	public ActionActive() {
	}

	public ActionActive(int actionActiveId, int permissionRoleId, int actionId) {
		this.actionActiveId = actionActiveId;
		this.permissionRoleId = permissionRoleId;
		this.actionId = actionId;
	}

	public int getActionActiveId() {
		return this.actionActiveId;
	}

	public void setActionActiveId(int actionActiveId) {
		this.actionActiveId = actionActiveId;
	}

	public int getPermissionRoleId() {
		return this.permissionRoleId;
	}

	public void setPermissionRoleId(int permissionRoleId) {
		this.permissionRoleId = permissionRoleId;
	}

	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

}
