package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * Actions generated by hbm2java
 */
public class Actions implements java.io.Serializable {

	private int actionId;
	private String actionCode;
	private String actionName;

	public Actions() {
	}

	public Actions(int actionId) {
		this.actionId = actionId;
	}

	public Actions(int actionId, String actionCode, String actionName) {
		this.actionId = actionId;
		this.actionCode = actionCode;
		this.actionName = actionName;
	}

	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

}
