package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * BillDetail generated by hbm2java
 */
public class BillDetail implements java.io.Serializable {

	private int billDetailId;
	private Integer productId;
	private Integer billId;
	private Integer quantity;
	private Integer bdprice;

	public BillDetail() {
	}

	public BillDetail(int billDetailId) {
		this.billDetailId = billDetailId;
	}

	public BillDetail(int billDetailId, Integer productId, Integer billId, Integer quantity, Integer bdprice) {
		this.billDetailId = billDetailId;
		this.productId = productId;
		this.billId = billId;
		this.quantity = quantity;
		this.bdprice = bdprice;
	}

	public int getBillDetailId() {
		return this.billDetailId;
	}

	public void setBillDetailId(int billDetailId) {
		this.billDetailId = billDetailId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getBdprice() {
		return this.bdprice;
	}

	public void setBdprice(Integer bdprice) {
		this.bdprice = bdprice;
	}

}
