package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Location generated by hbm2java
 */
@Data
@Entity
@Table(name = "Location", schema = "dbo", catalog = "hiep")
public class Location implements java.io.Serializable {
	@Id
	@Column(name = "AboutId")
	private Long locationId;
	
	@Basic
	@Column(name = "LocationName")
	private String locationName;

	public Location() {
	}

	public Location(String locationName) {
		this.locationName = locationName;
	}

	public Long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

}
