package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * MenuType generated by hbm2java
 */
public class MenuType implements java.io.Serializable {

	private Integer menuTypeId;
	private String menuName;

	public MenuType() {
	}

	public MenuType(String menuName) {
		this.menuName = menuName;
	}

	public Integer getMenuTypeId() {
		return this.menuTypeId;
	}

	public void setMenuTypeId(Integer menuTypeId) {
		this.menuTypeId = menuTypeId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

}
