package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * ProductCategory generated by hbm2java
 */
public class ProductCategory implements java.io.Serializable {

	private int categoryId;
	private String nameCate;
	private String meataTittle;
	private Integer parrentId;
	private Integer displayOrder;
	private String seoTittle;
	private Date createdDate;
	private String createBy;
	private Date modifiedDate;
	private String metaKeywords;
	private String metaDescription;
	private Boolean statuss;
	private Boolean showOnHome;

	public ProductCategory() {
	}

	public ProductCategory(int categoryId) {
		this.categoryId = categoryId;
	}

	public ProductCategory(int categoryId, String nameCate, String meataTittle, Integer parrentId, Integer displayOrder,
			String seoTittle, Date createdDate, String createBy, Date modifiedDate, String metaKeywords,
			String metaDescription, Boolean statuss, Boolean showOnHome) {
		this.categoryId = categoryId;
		this.nameCate = nameCate;
		this.meataTittle = meataTittle;
		this.parrentId = parrentId;
		this.displayOrder = displayOrder;
		this.seoTittle = seoTittle;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.statuss = statuss;
		this.showOnHome = showOnHome;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getNameCate() {
		return this.nameCate;
	}

	public void setNameCate(String nameCate) {
		this.nameCate = nameCate;
	}

	public String getMeataTittle() {
		return this.meataTittle;
	}

	public void setMeataTittle(String meataTittle) {
		this.meataTittle = meataTittle;
	}

	public Integer getParrentId() {
		return this.parrentId;
	}

	public void setParrentId(Integer parrentId) {
		this.parrentId = parrentId;
	}

	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	public String getSeoTittle() {
		return this.seoTittle;
	}

	public void setSeoTittle(String seoTittle) {
		this.seoTittle = seoTittle;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	public Boolean getStatuss() {
		return this.statuss;
	}

	public void setStatuss(Boolean statuss) {
		this.statuss = statuss;
	}

	public Boolean getShowOnHome() {
		return this.showOnHome;
	}

	public void setShowOnHome(Boolean showOnHome) {
		this.showOnHome = showOnHome;
	}

}
