package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * ProductImage generated by hbm2java
 */
public class ProductImage implements java.io.Serializable {

	private int productImageId;
	private String link;
	private Boolean main;

	public ProductImage() {
	}

	public ProductImage(int productImageId) {
		this.productImageId = productImageId;
	}

	public ProductImage(int productImageId, String link, Boolean main) {
		this.productImageId = productImageId;
		this.link = link;
		this.main = main;
	}

	public int getProductImageId() {
		return this.productImageId;
	}

	public void setProductImageId(int productImageId) {
		this.productImageId = productImageId;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Boolean getMain() {
		return this.main;
	}

	public void setMain(Boolean main) {
		this.main = main;
	}

}
