package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * ProductLocation generated by hbm2java
 */
public class ProductLocation implements java.io.Serializable {

	private int locationProductId;
	private int loctionId;
	private int produdctId;

	public ProductLocation() {
	}

	public ProductLocation(int locationProductId, int loctionId, int produdctId) {
		this.locationProductId = locationProductId;
		this.loctionId = loctionId;
		this.produdctId = produdctId;
	}

	public int getLocationProductId() {
		return this.locationProductId;
	}

	public void setLocationProductId(int locationProductId) {
		this.locationProductId = locationProductId;
	}

	public int getLoctionId() {
		return this.loctionId;
	}

	public void setLoctionId(int loctionId) {
		this.loctionId = loctionId;
	}

	public int getProdudctId() {
		return this.produdctId;
	}

	public void setProdudctId(int produdctId) {
		this.produdctId = produdctId;
	}

}
