package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private String role;

	public Roles() {
	}

	public Roles(int roleId) {
		this.roleId = roleId;
	}

	public Roles(int roleId, String roleName, String role) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.role = role;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
