package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * RolePermission generated by hbm2java
 */
public class RolePermission implements java.io.Serializable {

	private int rolePermissionId;
	private int roleId;
	private int permissionId;
	private int actionActive;

	public RolePermission() {
	}

	public RolePermission(int rolePermissionId, int roleId, int permissionId, int actionActive) {
		this.rolePermissionId = rolePermissionId;
		this.roleId = roleId;
		this.permissionId = permissionId;
		this.actionActive = actionActive;
	}

	public int getRolePermissionId() {
		return this.rolePermissionId;
	}

	public void setRolePermissionId(int rolePermissionId) {
		this.rolePermissionId = rolePermissionId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public int getActionActive() {
		return this.actionActive;
	}

	public void setActionActive(int actionActive) {
		this.actionActive = actionActive;
	}

}
