package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private String tagId;
	private String tagName;

	public Tags() {
	}

	public Tags(String tagId) {
		this.tagId = tagId;
	}

	public Tags(String tagId, String tagName) {
		this.tagId = tagId;
		this.tagName = tagName;
	}

	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

}
