package com.hiep.Entities;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userId;
	private String password;
	private Integer roleId;

	public Users() {
	}

	public Users(String userId) {
		this.userId = userId;
	}

	public Users(String userId, String password, Integer roleId) {
		this.userId = userId;
		this.password = password;
		this.roleId = roleId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
