package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * About generated by hbm2java
 */
@Data
@Entity
@Table(name = "About", schema = "dbo", catalog = "hiep")
public class AboutReq implements java.io.Serializable {
	@Id
	@Column(name = "AboutId")
	private int aboutId;
	@Basic
	@Column(name = "Tittle")
	private String tittle;
	@Basic
	@Column(name = "MetaTittle")
	private String metaTittle;
	@Basic
	@Column(name = "Descriptions")
	private String descriptions;
	@Basic
	@Column(name = "Details")
	private String details;
	@Basic
	@Column(name = "CreatedDate")
	private Date createdDate;
	@Basic
	@Column(name = "CreatedBy")
	private String createdBy;
	@Basic
	@Column(name = "ModifiedDate")
	private Date modifiedDate;
	@Basic
	@Column(name = "MetaKeywords")
	private String metaKeywords;
	@Basic
	@Column(name = "MetaDescription")
	private String metaDescription;

	public AboutReq() {
	}

	public AboutReq(int aboutId) {
		this.aboutId = aboutId;
	}

	public AboutReq(int aboutId, String tittle, String metaTittle, String descriptions, String details, Date createdDate,
			String createdBy, Date modifiedDate, String metaKeywords, String metaDescription) {
		this.aboutId = aboutId;
		this.tittle = tittle;
		this.metaTittle = metaTittle;
		this.descriptions = descriptions;
		this.details = details;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
	}

	
}
