package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ActionActive generated by hbm2java
 */
@Data
@Entity
@Table(name = "ActionActive", schema = "dbo", catalog = "hiep")
public class ActionActiveReq implements java.io.Serializable {

	@Id
	@Column(name = "AboutId")
	private int actionActiveId;
	@Basic
	@Column(name = "PermissionRoleId")
	private int permissionRoleId;
	@Basic
	@Column(name = "ActionId")
	private int actionId;

	public ActionActiveReq() {
	}

	public ActionActiveReq(int actionActiveId, int permissionRoleId, int actionId) {
		this.actionActiveId = actionActiveId;
		this.permissionRoleId = permissionRoleId;
		this.actionId = actionId;
	}


}
