package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Actions generated by hbm2java
 */
@Data
@Entity
@Table(name = "Actions", schema = "dbo", catalog = "hiep")
public class ActionsReq implements java.io.Serializable {

	@Id
	@Column(name = "AboutId")
	private int actionId;
	
	@Basic
	@Column(name = "ActionCode")
	private String actionCode;
	
	@Basic
	@Column(name = "ActionName")
	private String actionName;

	public ActionsReq() {
	}

	public ActionsReq(int actionId) {
		this.actionId = actionId;
	}

	public Actions(int actionId, String actionCode, String actionName) {
		this.actionId = actionId;
		this.actionCode = actionCode;
		this.actionName = actionName;
	}

	
}
