package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Bill generated by hbm2java
 */
@Data
@Entity
@Table(name = "Bill", schema = "dbo", catalog = "hiep")
public class BillReq implements java.io.Serializable {
	
	@Id
	@Column(name = "BillId")
	private int billId;
	
	@Id
	@Column(name = "CreatedDate")
	private Date createdDate;
	
	@Id
	@Column(name = "CreateBy")
	private String createBy;
	
	@Id
	@Column(name = "ModifiedDate")
	private Date modifiedDate;
	
	@Id
	@Column(name = "DeliverId")
	private int deliverId;
	
	@Id
	@Column(name = "TotalPrice")
	private Integer totalPrice;
	
	@Id
	@Column(name = "CustomerId")
	private Integer customerId;

	public BillReq() {
	}

	public BillReq(int billId, int deliverId) {
		this.billId = billId;
		this.deliverId = deliverId;
	}

	public BillReq(int billId, Date createdDate, String createBy, Date modifiedDate, int deliverId, Integer totalPrice,
			Integer customerId) {
		this.billId = billId;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.deliverId = deliverId;
		this.totalPrice = totalPrice;
		this.customerId = customerId;
	}

	
}
