package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Location generated by hbm2java
 */
@Data
public class LocationReq implements java.io.Serializable {

	private Long locationId;
	
	private String locationName;

	public LocationReq() {
	}

	public LocationReq(String locationName) {
		this.locationName = locationName;
	}


}
