package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Menu generated by hbm2java
 */

@Data
@Entity
@Table(name = "Menu", schema = "dbo", catalog = "hiep")
public class MenuReq implements java.io.Serializable {
	@Id
	@Column(name = "MenuId")
	private int menuId;
	
	@Basic
	@Column(name = "Texts")
	private String texts;
	
	@Basic
	@Column(name = "Link")
	private String link;
	
	@Basic
	@Column(name = "DisplayOrder")
	private Integer displayOrder;
	
	@Basic
	@Column(name = "Target")
	private String target;
	
	@Basic
	@Column(name = "Statuss")
	private Boolean statuss;
	
	@Basic
	@Column(name = "MenuTypeId")
	private Integer menuTypeId;
	
	@Basic
	@Column(name = "MenuParrenId")
	private Integer menuParrenId;

	public MenuReq() {
	}

	public MenuReq(int menuId) {
		this.menuId = menuId;
	}

	public MenuReq(int menuId, String texts, String link, Integer displayOrder, String target, Boolean statuss,
			Integer menuTypeId, Integer menuParrenId) {
		this.menuId = menuId;
		this.texts = texts;
		this.link = link;
		this.displayOrder = displayOrder;
		this.target = target;
		this.statuss = statuss;
		this.menuTypeId = menuTypeId;
		this.menuParrenId = menuParrenId;
	}


}
