package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * NewCategory generated by hbm2java
 */

@Data
@Entity
@Table(name = "NewCategory", schema = "dbo", catalog = "hiep")
public class NewCategoryReq implements java.io.Serializable {
	@Id
	@Column(name = "MenuTypeId")
	private int newCategoryId;
	
	@Basic
	@Column(name = "name")
	private String name;
	
	@Basic
	@Column(name = "meataTittle")
	private String meataTittle;
	
	@Basic
	@Column(name = "parrentId")
	private Integer parrentId;
	
	@Basic
	@Column(name = "displayOrder")
	private Integer displayOrder;
	
	@Basic
	@Column(name = "seoTittle")
	private String seoTittle;
	
	@Basic
	@Column(name = "createdDate")
	private Date createdDate;
	
	@Basic
	@Column(name = "createBy")
	private String createBy;
	
	@Basic
	@Column(name = "modifiedDate")
	private Date modifiedDate;
	
	@Basic
	@Column(name = "metaKeywords")
	private String metaKeywords;
	
	@Basic
	@Column(name = "metaDescription")
	private String metaDescription;
	
	@Basic
	@Column(name = "statuss")
	private Boolean statuss;
	
	@Basic
	@Column(name = "showOnHome")
	private Boolean showOnHome;

	public NewCategoryReq() {
	}

	public NewCategoryReq(int newCategoryId) {
		this.newCategoryId = newCategoryId;
	}

	public NewCategory(int newCategoryId, String name, String meataTittle, Integer parrentId, Integer displayOrder,
			String seoTittle, Date createdDate, String createBy, Date modifiedDate, String metaKeywords,
			String metaDescription, Boolean statuss, Boolean showOnHome) {
		this.newCategoryId = newCategoryId;
		this.name = name;
		this.meataTittle = meataTittle;
		this.parrentId = parrentId;
		this.displayOrder = displayOrder;
		this.seoTittle = seoTittle;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.statuss = statuss;
		this.showOnHome = showOnHome;
	}


}
