package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ProductCategory generated by hbm2java
 */
@Data
@Entity
@Table(name = "ProductCategory", schema = "dbo", catalog = "hiep")
public class ProductCategoryReq implements java.io.Serializable {
	@Id
	@Column(name = "CategoryId")
	private int categoryId;
	@Basic
	@Column(name = "NameCate")
	private String nameCate;
	@Basic
	@Column(name = "MeataTittle")
	private String meataTittle;
	@Basic
	@Column(name = "ParrentId")
	private Integer parrentId;
	@Basic
	@Column(name = "DisplayOrder")
	private Integer displayOrder;
	@Basic
	@Column(name = "SeoTittle")
	private String seoTittle;
	@Basic
	@Column(name = "CreatedDate")
	private Date createdDate;
	@Basic
	@Column(name = "CreateBy")
	private String createBy;
	@Basic
	@Column(name = "ModifiedDate")
	private Date modifiedDate;
	@Basic
	@Column(name = "MetaKeywords")
	private String metaKeywords;
	@Basic
	@Column(name = "MetaDescription")
	private String metaDescription;
	@Basic
	@Column(name = "Statuss")
	private Boolean statuss;
	@Basic
	@Column(name = "ShowOnHome")
	private Boolean showOnHome;

	public ProductCategoryReq() {
	}

	public ProductCategoryReq(int categoryId) {
		this.categoryId = categoryId;
	}

	public ProductCategoryReq(int categoryId, String nameCate, String meataTittle, Integer parrentId, Integer displayOrder,
			String seoTittle, Date createdDate, String createBy, Date modifiedDate, String metaKeywords,
			String metaDescription, Boolean statuss, Boolean showOnHome) {
		this.categoryId = categoryId;
		this.nameCate = nameCate;
		this.meataTittle = meataTittle;
		this.parrentId = parrentId;
		this.displayOrder = displayOrder;
		this.seoTittle = seoTittle;
		this.createdDate = createdDate;
		this.createBy = createBy;
		this.modifiedDate = modifiedDate;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.statuss = statuss;
		this.showOnHome = showOnHome;
	}

}
