package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Roles generated by hbm2java
 */
@Data
@Entity
@Table(name = "Roles", schema = "dbo", catalog = "hiep")
public class RolesReq implements java.io.Serializable {
	@Id
	@Column(name = "RoleId")
	private int roleId;
	@Basic
	@Column(name = "RoleName")
	private String roleName;
	@Basic
	@Column(name = "Role")
	private String role;
	

	public RolesReq() {
	}

	public RolesReq(int roleId) {
		this.roleId = roleId;
	}

	public RolesReq(int roleId, String roleName, String role) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.role = role;
	}

}
