package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Tags generated by hbm2java
 */
@Data
public class TagsReq implements java.io.Serializable {
	
	private String tagId;
	
	private String tagName;

	public TagsReq() {
	}

	public TagsReq(String tagId) {
		this.tagId = tagId;
	}

	public TagsReq(String tagId, String tagName) {
		this.tagId = tagId;
		this.tagName = tagName;
	}

	

}
