package com.hiep.EntitiesRequest;
// Generated Mar 16, 2020 10:55:25 AM by Hibernate Tools 5.4.7.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Users generated by hbm2java
 */
@Data
public class UsersReq implements java.io.Serializable {
	
	private String userId;
	
	private String password;

	private Integer roleId;

	public UsersReq() {
	}

	public UsersReq(String userId) {
		this.userId = userId;
	}

	public UsersReq(String userId, String password, Integer roleId) {
		this.userId = userId;
		this.password = password;
		this.roleId = roleId;
	}


}
